CREATE TABLE otp_codes (
    otp_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(45) NOT NULL,
    code VARCHAR(6) NOT NULL,
    expires_at DATETIME NOT NULL,
    is_used BOOLEAN NOT NULL DEFAULT FALSE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
